/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import java.awt.event.FocusEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.util.*;
import java.util.regex.*;
import java.awt.event.*;
import java.beans.Statement;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author jagab
 */
public class formss2 extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    ResultSet rs1;
    PreparedStatement pst;
    PreparedStatement pst1;
    String sql;
    String eno;
    String course;
    String name;
    int fee;
    String mode;
    private Object OptionPane;
    private String rno;
    /**
     * Creates new form formss2
     */
    public formss2() {
        initComponents();
        combo();
        eno="";
        this.setLocationRelativeTo(null);
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\PROJECT\\Login1\\Database12.accdb");
                txtname.setText("");
                txteno.setText("");
                txtcourse.setSelectedIndex(-1);
                fees1.setText("");
                txtcash.setSelected(false);
                txtcard.setSelected(false);
                txtcheque.setSelected(false);
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
        } catch (ClassNotFoundException ex) {
        }catch(SQLException ex){
        }
    }
    
    public void combo(){
    try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\PROJECT\\Login1\\Database12.accdb");
            String sql="select * from COURSE_MASTER";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String name=rs.getString("COURSE_NAME");
                txtcourse.addItem(name);
            }
    }
    catch(Exception e){
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txteno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcourse = new javax.swing.JComboBox<>();
        fees1 = new javax.swing.JTextField();
        txtcash = new javax.swing.JRadioButton();
        txtcheque = new javax.swing.JRadioButton();
        txtcard = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtadd = new javax.swing.JButton();
        txtmodify = new javax.swing.JButton();
        txtsearch = new javax.swing.JButton();
        txtreport = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        txtmin = new javax.swing.JLabel();
        txtclose = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txteno.setBackground(new java.awt.Color(204, 204, 204));
        txteno.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txteno.setEnabled(false);
        txteno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtenoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtenoMousePressed(evt);
            }
        });
        txteno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenoActionPerformed(evt);
            }
        });
        txteno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtenoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtenoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtenoKeyTyped(evt);
            }
        });
        getContentPane().add(txteno, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 321, 47));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT INFO MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 1100, 39));

        txtname.setBackground(new java.awt.Color(204, 204, 204));
        txtname.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtname.setEnabled(false);
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnameMousePressed(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameKeyTyped(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 321, 50));

        txtcourse.setBackground(new java.awt.Color(204, 204, 204));
        txtcourse.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        txtcourse.setEnabled(false);
        txtcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcourseMousePressed(evt);
            }
        });
        txtcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcourseActionPerformed(evt);
            }
        });
        txtcourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcourseKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcourseKeyTyped(evt);
            }
        });
        getContentPane().add(txtcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 321, 48));

        fees1.setBackground(new java.awt.Color(204, 204, 204));
        fees1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        fees1.setEnabled(false);
        fees1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fees1MousePressed(evt);
            }
        });
        fees1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fees1ActionPerformed(evt);
            }
        });
        fees1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fees1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fees1KeyTyped(evt);
            }
        });
        getContentPane().add(fees1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 321, 50));

        txtcash.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcash.setForeground(new java.awt.Color(255, 255, 255));
        txtcash.setSelected(true);
        txtcash.setText("Cash");
        txtcash.setEnabled(false);
        txtcash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcashMousePressed(evt);
            }
        });
        txtcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcashActionPerformed(evt);
            }
        });
        txtcash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcashKeyPressed(evt);
            }
        });
        getContentPane().add(txtcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        txtcheque.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcheque.setForeground(new java.awt.Color(255, 255, 255));
        txtcheque.setText("Cheque");
        txtcheque.setEnabled(false);
        txtcheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtchequeMousePressed(evt);
            }
        });
        txtcheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchequeActionPerformed(evt);
            }
        });
        txtcheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtchequeKeyPressed(evt);
            }
        });
        getContentPane().add(txtcheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        txtcard.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcard.setForeground(new java.awt.Color(255, 255, 255));
        txtcard.setText("Card");
        txtcard.setToolTipText("");
        txtcard.setEnabled(false);
        txtcard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcardMousePressed(evt);
            }
        });
        txtcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcardActionPerformed(evt);
            }
        });
        txtcard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcardKeyPressed(evt);
            }
        });
        getContentPane().add(txtcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("E.No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Course");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fees");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, 41));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Payment Mode");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, 41));

        txtadd.setBackground(new java.awt.Color(255, 204, 51));
        txtadd.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtadd.setText("Add");
        txtadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtaddMouseClicked(evt);
            }
        });
        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });
        txtadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaddKeyPressed(evt);
            }
        });
        getContentPane().add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 150, 70));

        txtmodify.setBackground(new java.awt.Color(255, 204, 51));
        txtmodify.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtmodify.setText("Modify");
        txtmodify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmodifyMouseClicked(evt);
            }
        });
        txtmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodifyActionPerformed(evt);
            }
        });
        getContentPane().add(txtmodify, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 154, 70));

        txtsearch.setBackground(new java.awt.Color(255, 204, 51));
        txtsearch.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtsearch.setText("Search");
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 145, 70));

        txtreport.setBackground(new java.awt.Color(255, 204, 51));
        txtreport.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        txtreport.setText("Report");
        txtreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreportActionPerformed(evt);
            }
        });
        getContentPane().add(txtreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 148, 71));

        l3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("click here to move to Login Page...");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 368, 26));

        txtmin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtmin.setForeground(new java.awt.Color(255, 255, 255));
        txtmin.setText("-");
        txtmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtminMouseClicked(evt);
            }
        });
        getContentPane().add(txtmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 20, 20));

        txtclose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtclose.setForeground(new java.awt.Color(255, 255, 255));
        txtclose.setText("X");
        txtclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcloseMouseClicked(evt);
            }
        });
        getContentPane().add(txtclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jButton1.setText("Quit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 540, 150, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sdbs9.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtenoMouseClicked
        // TODO add your handling code here:
        /*if(txtmodify.isEnabled()){
            txteno.setEditable(false);
        }
        else if(txtadd.isEnabled()){
            txteno.setEditable(true);
        }*/
    }//GEN-LAST:event_txtenoMouseClicked

    private void txtenoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtenoMousePressed
        // TODO add your handling code here:
        if(txteno.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Enrollment Number cannot be edited");
        }
    }//GEN-LAST:event_txtenoMousePressed

    private void txtenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenoActionPerformed
        // TODO add your handling code here:
        txteno=new JTextField();
        txteno.setText("23456");
    }//GEN-LAST:event_txtenoActionPerformed

    private void txtenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenoKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(txteno.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Values cannot be edited in this field");
            }
            else{
                txtname.requestFocus();
            }
        }
    }//GEN-LAST:event_txtenoKeyPressed

    private void txtenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenoKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,5}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txteno.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(this, "Enrollment Number is only 5 numbers");
        }
    }//GEN-LAST:event_txtenoKeyReleased

    private void txtenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenoKeyTyped
        // TODO add your handling code here:
        /*char c = evt.getKeyChar();

        if(!(Character.isDigit(c)||Character.isISOControl(c))){
            JOptionPane.showMessageDialog(null,"Only Numbers are Accepted");
            getToolkit().beep();
            evt.consume();
        }*/
        /*if(txteno.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Values cannot be edited in this field");
        }*/
        char c = evt.getKeyChar();

        if(!(Character.isISOControl(c))){
            JOptionPane.showMessageDialog(null,"Only Numbers are Accepted");
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtenoKeyTyped

    private void txtnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMousePressed
        // TODO add your handling code here:
        if(txtname.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Name of the Student cannot be edited");
        }
    }//GEN-LAST:event_txtnameMousePressed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(txtname.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Name needed to be filled");
            }
            else{
                txtcourse.requestFocus();
            }
        }

        //code for name textfield that accepts letter, whitespace and delete and backspace key only
        char c=evt.getKeyChar();
        //ISO control for edit operation(delete key and backspace key is allowed)
        if(!(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))){
            JOptionPane.showMessageDialog(null,"Only Alphabets are Accepted");
            getToolkit().beep();
            txtname.setEditable(false);
        }
        else{
            txtname.setEditable(true);
        }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        int position=txtname.getCaretPosition();
        txtname.setText(txtname.getText().toUpperCase());
        txtname.setCaretPosition(position);
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyTyped
        // TODO add your handling code here:
        /*if(txtname.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Name needed to be filled");
        }*/
        char c = evt.getKeyChar();

        if(!(Character.isISOControl(c))){
            JOptionPane.showMessageDialog(null,"Only Numbers are Accepted");
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtnameKeyTyped

    private void txtcourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcourseMousePressed
        // TODO add your handling code here:
        if(txtcourse.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Course cannot be edited");
        }
    }//GEN-LAST:event_txtcourseMousePressed

    private void txtcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcourseActionPerformed
        /* try {   // TODO add your handling code here:
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\PROJECT\\Login1\\Database12.accdb");
            String sql1="select * from Course_Master where Course_Name='"+txtcourse.getSelectedItem()+"'";
            pst1 = con.prepareStatement(sql1);
            rs1 = pst1.executeQuery();
            PreparedStatement pst = con.createStatement();
            rs= pst.executeQuery("select * from Course_Master");
            while(rs.next()){
                String Name=rs.getString("Course_Name");
                txtcourse.addItem("Name");
            }
            con.close();

        } catch(Exception e){

        }*/
    }//GEN-LAST:event_txtcourseActionPerformed

    private void txtcourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcourseKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(txtcourse.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(this,"Fees needed to be filled");
            }
            else{
                fees1.requestFocus();
            }
        }
    }//GEN-LAST:event_txtcourseKeyPressed

    private void txtcourseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcourseKeyTyped
        // TODO add your handling code here:
        /*if(txtcourse.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this,"Fees needed to be filled");
        }*/
        char c = evt.getKeyChar();

        if(!(Character.isDigit(c)||Character.isISOControl(c))){
            JOptionPane.showMessageDialog(null,"Only Numbers are Accepted");
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcourseKeyTyped

    private void fees1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fees1MousePressed
        // TODO add your handling code here:
        if(fees1.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Fees cannot be edited");
        }
    }//GEN-LAST:event_fees1MousePressed

    private void fees1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fees1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fees1ActionPerformed

    private void fees1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fees1KeyPressed
        // TODO add your handling code here:
        if(fees1.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Enrollment Number cannot be edited");
        }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(fees1.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Fees needed to be filled");
            }
            else{
                txtcash.requestFocus();
                txtcard.requestFocus();
                txtcheque.requestFocus();
            }
        }
    }//GEN-LAST:event_fees1KeyPressed

    private void fees1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fees1KeyTyped
        // TODO add your handling code here:
        if(fees1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Fees needed to be filled");
        }
        char c = evt.getKeyChar();

        if(!(Character.isISOControl(c))){
            JOptionPane.showMessageDialog(null,"Only Numbers are Accepted");
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_fees1KeyTyped

    private void txtcashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcashMousePressed
        // TODO add your handling code here:
        if(txtcash.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Cash option cannot be selected");
            txtcash.setSelected(false);
        }
    }//GEN-LAST:event_txtcashMousePressed

    private void txtcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcashActionPerformed
        // TODO add your handling code here
        if(txtcash.isSelected()){
            txtcard.setSelected(false);
            txtcheque.setSelected(false);
        }
    }//GEN-LAST:event_txtcashActionPerformed

    private void txtcashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcashKeyPressed
        // TODO add your handling code here:
        if(txtcash.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Enrollment Number cannot be edited");
        }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            txtadd.requestFocus();
        }
    }//GEN-LAST:event_txtcashKeyPressed

    private void txtchequeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtchequeMousePressed
        // TODO add your handling code here:
        if(txtcheque.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Cheque option cannot be selected");
            txtcheque.setSelected(false);
        }
    }//GEN-LAST:event_txtchequeMousePressed

    private void txtchequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchequeActionPerformed
        // TODO add your handling code here:
        if(txtcheque.isSelected()){
            txtcash.setSelected(false);
            txtcard.setSelected(false);
        }
    }//GEN-LAST:event_txtchequeActionPerformed

    private void txtchequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchequeKeyPressed
        // TODO add your handling code here:
        if(txtcheque.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Enrollment Number cannot be edited");
        }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            txtadd.requestFocus();
        }
    }//GEN-LAST:event_txtchequeKeyPressed

    private void txtcardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcardMousePressed
        // TODO add your handling code here:
        if(txtcard.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Card option cannot be selected");
            txtcard.setSelected(false);
        }
    }//GEN-LAST:event_txtcardMousePressed

    private void txtcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcardActionPerformed
        // TODO add your handling code here:
        if(txtcard.isSelected()){
            txtcash.setSelected(false);
            txtcheque.setSelected(false);
        }
    }//GEN-LAST:event_txtcardActionPerformed

    private void txtcardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcardKeyPressed
        // TODO add your handling code here:
        if(txtcard.isRequestFocusEnabled()){
            JOptionPane.showMessageDialog(this,"Enrollment Number cannot be edited");
        }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            txtadd.requestFocus();
        }
    }//GEN-LAST:event_txtcardKeyPressed

    private void txtaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddMouseClicked

    private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed

        try{
            if(txtadd.isEnabled()){
                formss2_1 f21=new formss2_1();
                f21.setVisible(true);
                f21.pack();
                f21.show();
                dispose();
            }
            else
            {
                cf();
            }
        }
        catch(Exception ex){

        }
        /*try {
            // TODO add your handling code here:
            //auto_eno();
            boolean b=false;
            if(txtname.getText().equals("")){
                b=false;
                JOptionPane.showMessageDialog(null,"Kindly enter the student name");
                txtname.requestFocus();
            }
            else if(txteno.getText().equals("")){
                b=false;
                JOptionPane.showMessageDialog(null,"Kindly enter the student enrollment number");
                txteno.requestFocus();
            }
            else if(txtcourse.getSelectedItem().equals("")){
                b=false;
                JOptionPane.showMessageDialog(this,"Kindly enter the opted course");
                txtcourse.requestFocus();
            }
            else if(fees.getText().equals("")){
                b=false;
                JOptionPane.showMessageDialog(null,"Kindly enter the fees of the opted course");
                fees.requestFocus();
            }
            else{
                String enrol=txteno.getText();
                pst=con.prepareStatement("select eno from dbs where eno=?");
                pst.setString(1,enrol);
                rs=pst.executeQuery();
                if(rs.next()==true){
                    JOptionPane.showMessageDialog(this,"This data already Exsist");
                }
                else{
                    pst=con.prepareStatement("insert into dbs(name,eno,course,fees,mode)values(?,?,?,?,?)");
                    pst.setString(1, txtname.getText());
                    pst.setString(2, txteno.getText());
                    pst.setString(3, txtcourse.getSelectedItem().toString());
                    pst.setString(4, fees.getText());
                    if(txtcash.isSelected()){
                        pst.setString(5,txtcash.getText());
                    }
                    else if(txtcard.isSelected()){
                        pst.setString(5, txtcard.getText());
                    }
                    else{
                        pst.setString(5,txtcheque.getText());
                    }
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Data is added successfully");
                    clearfields();

                }
            }
        }
        catch (SQLException ex) {
        }*/
    }//GEN-LAST:event_txtaddActionPerformed

    private void txtaddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            formss2_1 f22=new formss2_1();
            f22.setVisible(true);
            f22.pack();
            f22.show();
            dispose();
        }
    }//GEN-LAST:event_txtaddKeyPressed

    private void txtmodifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmodifyMouseClicked
        // TODO add your handling code here:
        txteno.setEditable(false);
    }//GEN-LAST:event_txtmodifyMouseClicked

    private void txtmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodifyActionPerformed
        // TODO add your handling code here:
        forms2_2 f22=new forms2_2();
        f22.setVisible(true);
        f22.pack();
        f22.show();
        dispose();
    }//GEN-LAST:event_txtmodifyActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
        formss2_3 f23=new formss2_3();
        f23.show();
        f23.setVisible(true);
        f23.pack();
        dispose();
        /*try{

            clearfields();
            String s = JOptionPane.showInputDialog(this,"Enter eno for search");
            String enrol=txteno.getText();
            pst=con.prepareStatement("select eno from dbs where eno=?");
            pst.setString(1,s);
            rs1=pst.executeQuery();
            if(rs1.next()){
                pst=con.prepareStatement("select * from dbs where eno=?");
                pst.setString(1, s);
                rs=pst.executeQuery();
                if(rs.next()){
                    txtname.setText(rs.getString(5));
                    txteno.setText(rs.getString(4));
                    txtcourse.setSelectedItem(rs.getString(2));
                    fees.setText(rs.getString(1));
                    String mode=rs.getString(3);
                    if(mode.equals("Cash"))
                    {
                        txtcash.setSelected(true);
                    }
                    else if(mode.equals("Card"))
                    {
                        txtcard.setSelected(true);
                    }
                    else if(mode.equals("Cheque"))
                    {
                        txtcheque.setSelected(true);
                    }
                }
            }
            else if(!(rs1.next())){
                JOptionPane.showMessageDialog(this,"No such student data is found");
            }
        } catch (SQLException ex) {
        }*/
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreportActionPerformed
        // TODO add your handling code here:
        reports r=new reports();
        r.setVisible(true);
        r.pack();
        r.show();
        dispose();
    }//GEN-LAST:event_txtreportActionPerformed

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
        logindb1 lb=new logindb1();
        lb.setVisible(true);
        lb.pack();
        lb.show();
        dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void txtminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtminMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_txtminMouseClicked

    private void txtcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtcloseMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    
    public void clearfields(){
        txtname.setText("");
        txteno.setText("");
        txtcourse.setSelectedIndex(-1);
        fees1.setText("");
        txtcash.setSelected(false);
        txtcard.setSelected(false);
        txtcheque.setSelected(false);
        //txtupdate.setVisible(false);
        //txtdelete2.setVisible(false);
        
    }
    public void cf(){
        txtname.setText("");
        txteno.setText("");
        txtcourse.setSelectedIndex(-1);
        fees1.setText("");
        txtcash.setSelected(true);
        txtcard.setSelected(false);
        txtcheque.setSelected(false);
        //txtsave.setVisible(false);
        //txtmodify.setVisible(true);
        //txtupdate.setVisible(false);
        //txtdelete2.setVisible(false);
        txtsearch.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formss2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formss2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formss2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formss2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formss2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fees1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel l3;
    private javax.swing.JButton txtadd;
    private javax.swing.JRadioButton txtcard;
    private javax.swing.JRadioButton txtcash;
    private javax.swing.JRadioButton txtcheque;
    private javax.swing.JLabel txtclose;
    private javax.swing.JComboBox<String> txtcourse;
    private javax.swing.JTextField txteno;
    private javax.swing.JLabel txtmin;
    private javax.swing.JButton txtmodify;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton txtreport;
    private javax.swing.JButton txtsearch;
    // End of variables declaration//GEN-END:variables
}
