/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JFrame;

/**
 *
 * @author jagab
 */
public class reposhead extends javax.swing.JFrame {

    /**
     * Creates new form reposhead
     */
    public reposhead() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmin1 = new javax.swing.JLabel();
        txtclose = new javax.swing.JLabel();
        txtlabel = new javax.swing.JLabel();
        txtcombo = new javax.swing.JComboBox<>();
        l3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT DATABASE REPORT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 850, 39));

        txtmin1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtmin1.setForeground(new java.awt.Color(255, 255, 255));
        txtmin1.setText("-");
        txtmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmin1MouseClicked(evt);
            }
        });
        getContentPane().add(txtmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 20, 20));

        txtclose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtclose.setForeground(new java.awt.Color(255, 255, 255));
        txtclose.setText("X");
        txtclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcloseMouseClicked(evt);
            }
        });
        getContentPane().add(txtclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        txtlabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtlabel.setForeground(new java.awt.Color(255, 255, 255));
        txtlabel.setText("Search");
        getContentPane().add(txtlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 216, 113, 73));

        txtcombo.setBackground(new java.awt.Color(221, 146, 33));
        txtcombo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcombo.setForeground(new java.awt.Color(255, 255, 255));
        txtcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eno", "Name", "Course", "Fees", "Mode", " " }));
        txtcombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtcomboItemStateChanged(evt);
            }
        });
        txtcombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcomboMouseClicked(evt);
            }
        });
        txtcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomboActionPerformed(evt);
            }
        });
        txtcombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcomboKeyPressed(evt);
            }
        });
        getContentPane().add(txtcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 216, 337, 73));

        l3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("click here to move back to report form...");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 410, 26));

        jButton6.setBackground(new java.awt.Color(255, 204, 51));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jButton6.setText("Quit");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 150, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reop1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmin1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_txtmin1MouseClicked

    private void txtcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtcloseMouseClicked

    private void txtcomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtcomboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomboItemStateChanged

    private void txtcomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcomboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomboMouseClicked

    private void txtcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomboActionPerformed
        // TODO add your handling code here:
        if(txtcombo.getSelectedItem()=="Course"){
            reposcourse c=new reposcourse();
            c.setVisible(true);
            c.pack();
            c.show();
            dispose();
        }
        else if(txtcombo.getSelectedItem()=="Mode"){
            reposmode m=new reposmode();
            m.setVisible(true);
            m.pack();
            m.show();
            dispose();
            
        }
        else if(txtcombo.getSelectedItem()=="Name"){
            reposnam n=new reposnam();
            n.setVisible(true);
            n.pack();
            n.show();
            dispose();
        }
        else if(txtcombo.getSelectedItem()=="Eno"){
            respoen e=new respoen();
            e.setVisible(true);
            e.pack();
            e.show();
            dispose();
        }
        else if(txtcombo.getSelectedItem()=="Fees"){
            respofees f=new respofees();
            f.setVisible(true);
            f.pack();
            f.show();
            dispose();
        }
    }//GEN-LAST:event_txtcomboActionPerformed

    private void txtcomboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomboKeyPressed
        // TODO add your handling code here:
        /*if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(txtcombo.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(this,"Fees needed to be filled");
            }
            else{
                txtfield.requestFocus();
            }
        }*/
    }//GEN-LAST:event_txtcomboKeyPressed

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
        logindb1 lb=new logindb1();
        lb.setVisible(true);
        lb.pack();
        lb.show();
        dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reposhead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reposhead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reposhead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reposhead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reposhead().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel txtclose;
    private javax.swing.JComboBox<String> txtcombo;
    private javax.swing.JLabel txtlabel;
    private javax.swing.JLabel txtmin1;
    // End of variables declaration//GEN-END:variables
}
