/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.Connection;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author jagab
 */
public class reposmode extends javax.swing.JFrame {
    DefaultTableModel dm;
    ButtonGroup bg=new ButtonGroup();
    private int d;
    Connection con;
    java.sql.ResultSet rs;
    java.sql.ResultSet rs1;
    java.sql.PreparedStatement pst;
    java.sql.PreparedStatement pst1;
    String sql;

    /**
     * Creates new form reposmode
     */
    public reposmode() {
        initComponents();
        //CreateColumns();
        txtdata.setVisible(false);
        this.setLocationRelativeTo(null);
        try{
           Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           con = java.sql.DriverManager.getConnection("jdbc:ucanaccess://D:\\PROJECT\\Login1\\Database12.accdb");
           pst=con.prepareStatement("select * from dbs");
           rs=pst.executeQuery();
           ResultSetMetaData rsmd=(ResultSetMetaData) rs.getMetaData();
           int n = rsmd.getColumnCount();
           DefaultTableModel dtm=(DefaultTableModel) txtdata.getModel();
           dtm.setRowCount(0);
           while(rs.next()){
               Vector v=new Vector();
               for(int i=1;i<=n;i++){
                   v.add(rs.getString("eno"));
                   v.add(rs.getString("name"));
                   v.add(rs.getString("course"));
                   v.add(rs.getString("fees"));
                   v.add(rs.getString("mode"));
               }
               dtm.addRow(v);
           }
              
        } catch (ClassNotFoundException ex) {
        }catch(SQLException ex){
        }
        addToGroup();
        Connection con;
    java.sql.PreparedStatement pst;
    java.sql.ResultSet rs;
    }
    
    private void addToGroup(){
        bg.add(txtcash);
        bg.add(txtcard);
        bg.add(txtcheque);
    }
    
    private void CreateColumns(){
        this.setLocationRelativeTo(null);
        dm=(DefaultTableModel) txtdata.getModel();
        
        
        
    }

    
    private void Populate(String name,String eno,String course,String fees,String mode){
        String[] rowData={eno,name,course,fees,mode};
        dm.addRow(rowData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmin1 = new javax.swing.JLabel();
        txtclose = new javax.swing.JLabel();
        txtlabel = new javax.swing.JLabel();
        txtcash = new javax.swing.JRadioButton();
        txtcard = new javax.swing.JRadioButton();
        txtcheque = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdata = new javax.swing.JTable();
        l3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT DATABASE REPORT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 850, 39));

        txtmin1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtmin1.setForeground(new java.awt.Color(255, 255, 255));
        txtmin1.setText("-");
        txtmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmin1MouseClicked(evt);
            }
        });
        getContentPane().add(txtmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 20, 20));

        txtclose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtclose.setForeground(new java.awt.Color(255, 255, 255));
        txtclose.setText("X");
        txtclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcloseMouseClicked(evt);
            }
        });
        getContentPane().add(txtclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        txtlabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtlabel.setForeground(new java.awt.Color(255, 255, 255));
        txtlabel.setText("Search");
        getContentPane().add(txtlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 113, 73));

        txtcash.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        txtcash.setForeground(new java.awt.Color(255, 255, 255));
        txtcash.setText("Cash");
        txtcash.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtcashItemStateChanged(evt);
            }
        });
        txtcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcashActionPerformed(evt);
            }
        });
        getContentPane().add(txtcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        txtcard.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtcard.setForeground(new java.awt.Color(255, 255, 255));
        txtcard.setText("Card");
        txtcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcardActionPerformed(evt);
            }
        });
        getContentPane().add(txtcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        txtcheque.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtcheque.setForeground(new java.awt.Color(255, 255, 255));
        txtcheque.setText("Cheque");
        txtcheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchequeActionPerformed(evt);
            }
        });
        getContentPane().add(txtcheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        txtdata.setBackground(new java.awt.Color(221, 146, 33));
        txtdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Eno", "Name", "Course", "Fees", "Payment mode"
            }
        ));
        txtdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txtdata);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 940, 310));

        l3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("click here to move back to data form...");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 410, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reop1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmin1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_txtmin1MouseClicked

    private void txtcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtcloseMouseClicked

    private void txtcashItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtcashItemStateChanged
        // TODO add your handling code here:
        //String query=getSelected();
        //filter(query);
    }//GEN-LAST:event_txtcashItemStateChanged

    private void txtcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcashActionPerformed
        // TODO add your handling code here:
        if(txtcash.isSelected()){
            txtdata.setVisible(true);
            DefaultTableModel ob=(DefaultTableModel) txtdata.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
        txtdata.setRowSorter(obj);
        obj.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)"+txtcash.getText()));
        txtdata.setVisible(true);
        if(txtcash.getSelectedIcon().equals("")){
            txtdata.setVisible(false);
        }
        }
        else{
            txtdata.setVisible(false);
        }
    }//GEN-LAST:event_txtcashActionPerformed

    private void txtcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcardActionPerformed
        // TODO add your handling code here:
          if(txtcard.isSelected()){
            txtdata.setVisible(true);
            DefaultTableModel ob=(DefaultTableModel) txtdata.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
        txtdata.setRowSorter(obj);
        obj.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)"+txtcard.getText()));
        txtdata.setVisible(true);
        if(txtcard.getSelectedIcon().equals("")){
            txtdata.setVisible(false);
        }
        }
        else{
            txtdata.setVisible(false);
        }
    }//GEN-LAST:event_txtcardActionPerformed

    private void txtchequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchequeActionPerformed
        // TODO add your handling code here:
        if(txtcheque.isSelected()){
            txtdata.setVisible(true);
            DefaultTableModel ob=(DefaultTableModel) txtdata.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
        txtdata.setRowSorter(obj);
        obj.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)"+txtcheque.getText()));
        txtdata.setVisible(true);
        if(txtcheque.getSelectedIcon().equals("")){
            txtdata.setVisible(false);
        }
        }
        else{
            txtdata.setVisible(false);
        }
    }//GEN-LAST:event_txtchequeActionPerformed

    private void txtdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdataMouseClicked
        // TODO add your handling code here:
        boolean a=txtdata.isEditing();
        if(a==false){
            JOptionPane.showMessageDialog(null,"Data report cannot be edited");
        }
    }//GEN-LAST:event_txtdataMouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
        reposhead rh=new reposhead();
        rh.setVisible(true);
        rh.pack();
        rh.show();
        dispose();
    }//GEN-LAST:event_l3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reposmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reposmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reposmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reposmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reposmode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l3;
    private javax.swing.JRadioButton txtcard;
    private javax.swing.JRadioButton txtcash;
    private javax.swing.JRadioButton txtcheque;
    private javax.swing.JLabel txtclose;
    private javax.swing.JTable txtdata;
    private javax.swing.JLabel txtlabel;
    private javax.swing.JLabel txtmin1;
    // End of variables declaration//GEN-END:variables
}
