/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author jagab
 */
public class welcomepages extends javax.swing.JFrame {
    private int d;
    Connection con;
    ResultSet rs;
    ResultSet rs1;
    java.sql.PreparedStatement pst;
    java.sql.PreparedStatement pst1;
    String sql;

    /**
     * Creates new form welcomepages
     */
    public welcomepages() {
        initComponents();
        this.setLocationRelativeTo(null);
        combo();
        txtcourse.setSelectedIndex(-1);
        txtnotes.setVisible(false);
        txteb.setVisible(false);
        txtrec.setVisible(false);
        txtass.setVisible(false);
        txtex.setVisible(false);
        txtpro1.setVisible(false);
        
    }

    public void combo(){
    try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = java.sql.DriverManager.getConnection("jdbc:ucanaccess://D:\\PROJECT\\Login1\\Database12.accdb");
            String sql="select * from subject";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String name=rs.getString("SUBJECT_NAME");
                txtcourse.addItem(name);
            }
    }
    catch(Exception e){
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtmin = new javax.swing.JLabel();
        txtclose = new javax.swing.JLabel();
        txtlabel = new javax.swing.JLabel();
        txtnotes = new javax.swing.JLabel();
        txteb = new javax.swing.JLabel();
        txtrec = new javax.swing.JLabel();
        txtass = new javax.swing.JLabel();
        txtex = new javax.swing.JLabel();
        txtpro1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        txtcourse = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        txtpro.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtpro.setText("PROJECTS");
        txtpro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtproMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO EBOOKS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 680, 39));

        txtmin.setFont(new java.awt.Font("Times New Roman", 1, 42)); // NOI18N
        txtmin.setForeground(new java.awt.Color(255, 255, 255));
        txtmin.setText("-");
        txtmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtminMouseClicked(evt);
            }
        });
        getContentPane().add(txtmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 20, 10));

        txtclose.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        txtclose.setForeground(new java.awt.Color(255, 255, 255));
        txtclose.setText("X");
        txtclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcloseMouseClicked(evt);
            }
        });
        getContentPane().add(txtclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        txtlabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtlabel.setForeground(new java.awt.Color(255, 255, 255));
        txtlabel.setText("Search ");
        getContentPane().add(txtlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, 73));

        txtnotes.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtnotes.setForeground(new java.awt.Color(255, 255, 255));
        txtnotes.setText("NOTES");
        txtnotes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtnotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnotesMouseClicked(evt);
            }
        });
        getContentPane().add(txtnotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 123, 33));

        txteb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txteb.setForeground(new java.awt.Color(255, 255, 255));
        txteb.setText("E-BOOKS");
        txteb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txteb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtebMouseClicked(evt);
            }
        });
        getContentPane().add(txteb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 142, 46));

        txtrec.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtrec.setForeground(new java.awt.Color(255, 255, 255));
        txtrec.setText("RECORDINGS");
        txtrec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtrec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrecMouseClicked(evt);
            }
        });
        getContentPane().add(txtrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 33));

        txtass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtass.setForeground(new java.awt.Color(255, 255, 255));
        txtass.setText("ASSINGNMENTS");
        txtass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtassMouseClicked(evt);
            }
        });
        getContentPane().add(txtass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 33));

        txtex.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtex.setForeground(new java.awt.Color(255, 255, 255));
        txtex.setText("EXCERCISES");
        txtex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexMouseClicked(evt);
            }
        });
        getContentPane().add(txtex, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, 33));

        txtpro1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtpro1.setForeground(new java.awt.Color(255, 255, 255));
        txtpro1.setText("PROJECTS");
        txtpro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtpro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpro1MouseClicked(evt);
            }
        });
        getContentPane().add(txtpro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 162, 33));

        l3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("click here to move to Login Page...");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 368, 26));

        txtcourse.setBackground(new java.awt.Color(221, 146, 33));
        txtcourse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtcourse.setForeground(new java.awt.Color(255, 255, 255));
        txtcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C++", "JAVA", "PYTHON", "HTML & CSS", "SQL", "BOOTSTRAP", "SPRINGBOOT", "RUBY", "PEARL", "R PROGRAMMING", "TALLY", " " }));
        txtcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcourseActionPerformed(evt);
            }
        });
        getContentPane().add(txtcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 384, 73));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Quit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 140, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mod7.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtminMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_txtminMouseClicked

    private void txtcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtcloseMouseClicked

    private void txtnotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnotesMouseClicked
        // TODO add your handling code here:
        /*if(txtcourse.setSelectedIndex(2))){
        notes n=new n();
        n.setVisible(true);
        n.pack();
        n.show();
        dispose();
        }*/
        if(txtcourse.getSelectedItem()=="PYTHON"){
            pynotes n=new pynotes();
            n.setVisible(true);
            n.pack();
            n.show();
            dispose();
        }
    }//GEN-LAST:event_txtnotesMouseClicked

    private void txtebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtebMouseClicked
        // TODO add your handling code here:
        if(txtcourse.getSelectedItem()=="JAVA"){
            bookj ja=new bookj();
            ja.setVisible(true);
            ja.pack();
            ja.show();
            dispose();
        }
        else if(txtcourse.getSelectedItem()=="PYTHON"){
            bookpy py=new bookpy();
            py.setVisible(true);
            py.pack();
            py.show();
            dispose();
        }
        else if(txtcourse.getSelectedItem()=="C"){
            bookc c=new bookc();
            c.setVisible(true);
            c.pack();
            c.show();
            dispose();
        }
        else if(txtcourse.getSelectedItem()=="C++"){
            bookcpp cpp=new bookcpp();
            cpp.setVisible(true);
            cpp.pack();
            cpp.show();
            dispose();
        }
        else if(txtcourse.getSelectedItem()=="HTML & CSS"){
            bookhc hc=new bookhc();
            hc.setVisible(true);
            hc.pack();
            hc.show();
            dispose();
        }
    }//GEN-LAST:event_txtebMouseClicked

    private void txtrecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrecMouseClicked
        // TODO add your handling code here:
            formssrec r=new formssrec();
            r.setVisible(true);
            r.pack();
            r.show();
            dispose();
    }//GEN-LAST:event_txtrecMouseClicked

    private void txtassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtassMouseClicked
        // TODO add your handling code here:
        formsassign a=new formsassign();
        a.setVisible(true);
        a.pack();
        a.show();
        dispose();
    }//GEN-LAST:event_txtassMouseClicked

    private void txtexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexMouseClicked
        // TODO add your handling code here:
        formssexcer e= new formssexcer();
        e.setVisible(true);
        e.pack();
        e.show();
        dispose();
    }//GEN-LAST:event_txtexMouseClicked

    private void txtproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtproMouseClicked
        // TODO add your handling code here:
        formsspro pro=new formsspro();
        pro.setVisible(true);
        pro.pack();
        pro.show();
        dispose();
    }//GEN-LAST:event_txtproMouseClicked

    private void txtpro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpro1MouseClicked
        // TODO add your handling code here:
        formsspro pro=new formsspro();
        pro.setVisible(true);
        pro.pack();
        pro.show();
        dispose();
    }//GEN-LAST:event_txtpro1MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
        logindb1 lb=new logindb1();
        lb.setVisible(true);
        lb.pack();
        lb.show();
        dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void txtcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcourseActionPerformed
        // TODO add your handling code here:
        if(txtcourse.isEnabled()){
            txtnotes.setVisible(true);
            txteb.setVisible(true);
            txtrec.setVisible(true);
            txtass.setVisible(true);
            txtex.setVisible(true);
            txtpro1.setVisible(true);
        }
        else{
            txtnotes.setVisible(false);
            txteb.setVisible(false);
            txtrec.setVisible(false);
            txtass.setVisible(false);
            txtex.setVisible(false);
            txtpro1.setVisible(false);
        }
    }//GEN-LAST:event_txtcourseActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomepages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomepages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomepages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomepages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomepages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel txtass;
    private javax.swing.JLabel txtclose;
    private javax.swing.JComboBox<String> txtcourse;
    private javax.swing.JLabel txteb;
    private javax.swing.JLabel txtex;
    private javax.swing.JLabel txtlabel;
    private javax.swing.JLabel txtmin;
    private javax.swing.JLabel txtnotes;
    private javax.swing.JLabel txtpro;
    private javax.swing.JLabel txtpro1;
    private javax.swing.JLabel txtrec;
    // End of variables declaration//GEN-END:variables
}
